#!/bin/sh
# macosx-bsd-eye.sh
# Aqua/Panther/Tiger-inspired eye-candy preset for FreeBSD + X11 + Openbox.
#
# Usage as root:
#   sh macosx-bsd-eye.sh USER [aqua|graphite|tiger]
#
# Example:
#   sh macosx-bsd-eye.sh w3r aqua
#
# Then login as USER and run:
#   startx
#
# This script does NOT use Apple assets. It only creates Aqua-inspired colors/configs.

set -eu

die() {
  echo "ERROR: $*" >&2
  exit 1
}

info() {
  echo "==> $*"
}

warn() {
  echo "WARN: $*" >&2
}

[ "$(uname -s)" = "FreeBSD" ] || die "This script is intended for FreeBSD."
[ "$(id -u)" -eq 0 ] || die "Run as root: sh $0 USER [aqua|graphite|tiger]"

USER_NAME="${1:-}"
PROFILE="${2:-aqua}"

[ -n "$USER_NAME" ] || die "Usage: sh $0 USER [aqua|graphite|tiger]"
id "$USER_NAME" >/dev/null 2>&1 || die "User '$USER_NAME' does not exist."

USER_HOME="$(pw usershow "$USER_NAME" | awk -F: '{print $9}')"
[ -d "$USER_HOME" ] || die "Home directory not found: $USER_HOME"

case "$PROFILE" in
  aqua)
    THEME_NAME="AquaBSD"
    TOP="#d7ecff"
    MID="#69aef5"
    BOT="#1b64b0"
    TITLE_TEXT="#ffffff"
    INACTIVE_TOP="#eeeeee"
    INACTIVE_BOT="#bfc8d0"
    WALL_R1=38;  WALL_G1=95;  WALL_B1=175
    WALL_R2=128; WALL_G2=192; WALL_B2=255
    PANEL="#eef7ff"
    ACCENT="#2b83d3"
    ;;
  graphite)
    THEME_NAME="GraphiteBSD"
    TOP="#f2f4f6"
    MID="#bfc8d1"
    BOT="#6d7b89"
    TITLE_TEXT="#ffffff"
    INACTIVE_TOP="#eeeeee"
    INACTIVE_BOT="#c7c7c7"
    WALL_R1=62;  WALL_G1=70;  WALL_B1=82
    WALL_R2=186; WALL_G2=198; WALL_B2=212
    PANEL="#f5f6f7"
    ACCENT="#6d7b89"
    ;;
  tiger)
    THEME_NAME="TigerBSD"
    TOP="#e7f5ff"
    MID="#71c5ff"
    BOT="#0e75c9"
    TITLE_TEXT="#ffffff"
    INACTIVE_TOP="#f6f6f6"
    INACTIVE_BOT="#d4d4d4"
    WALL_R1=8;   WALL_G1=62;  WALL_B1=124
    WALL_R2=94;  WALL_G2=189; WALL_B2=255
    PANEL="#f8fbff"
    ACCENT="#0e75c9"
    ;;
  *)
    die "Unknown profile '$PROFILE'. Use: aqua, graphite, tiger"
    ;;
esac

install_pkg() {
  PKG="$1"
  if pkg info -e "$PKG" >/dev/null 2>&1; then
    return 0
  fi
  info "Installing package: $PKG"
  if ! pkg install -y "$PKG"; then
    warn "Could not install '$PKG'. Continuing anyway."
  fi
}

info "Bootstrapping pkg if needed..."
env ASSUME_ALWAYS_YES=yes pkg bootstrap -f >/dev/null 2>&1 || true

info "Updating pkg metadata..."
pkg update || warn "pkg update failed; trying to continue."

info "Installing eye-candy packages..."
install_pkg openbox
install_pkg xterm
install_pkg picom
install_pkg feh
install_pkg tint2
install_pkg lxappearance
install_pkg fontconfig
install_pkg dejavu
install_pkg webfonts

TS="$(date +%Y%m%d-%H%M%S)"

backup_path() {
  P="$1"
  if [ -e "$P" ]; then
    cp -Rp "$P" "$P.backup.$TS"
    info "Backup: $P.backup.$TS"
  fi
}

backup_path "$USER_HOME/.config/openbox"
backup_path "$USER_HOME/.config/picom"
backup_path "$USER_HOME/.config/tint2"
backup_path "$USER_HOME/.themes/$THEME_NAME"
backup_path "$USER_HOME/.Xresources"
backup_path "$USER_HOME/.gtkrc-2.0"
backup_path "$USER_HOME/.config/gtk-3.0/settings.ini"

info "Creating directories..."
mkdir -p \
  "$USER_HOME/.config/openbox" \
  "$USER_HOME/.config/picom" \
  "$USER_HOME/.config/tint2" \
  "$USER_HOME/.config/gtk-3.0" \
  "$USER_HOME/.themes/$THEME_NAME/openbox-3" \
  "$USER_HOME/Pictures"

info "Generating Aqua-like wallpaper..."
WALL="$USER_HOME/Pictures/${THEME_NAME}-wallpaper.ppm"
awk -v w=1280 -v h=800 \
    -v r1="$WALL_R1" -v g1="$WALL_G1" -v b1="$WALL_B1" \
    -v r2="$WALL_R2" -v g2="$WALL_G2" -v b2="$WALL_B2" '
BEGIN {
  print "P3";
  print w " " h;
  print "255";
  for (y = 0; y < h; y++) {
    t = y / (h - 1);
    # Vertical Aqua-ish gradient.
    r = int(r1 * (1 - t) + r2 * t);
    g = int(g1 * (1 - t) + g2 * t);
    b = int(b1 * (1 - t) + b2 * t);

    # Soft bright horizontal band, like old shiny wallpapers.
    band = exp(-((t - 0.34) * (t - 0.34)) / 0.008) * 42;
    r = r + band; g = g + band; b = b + band;

    # Slight darker bottom.
    if (t > 0.72) {
      d = (t - 0.72) * 55;
      r -= d; g -= d; b -= d;
    }

    if (r < 0) r = 0; if (g < 0) g = 0; if (b < 0) b = 0;
    if (r > 255) r = 255; if (g > 255) g = 255; if (b > 255) b = 255;

    for (x = 0; x < w; x++) {
      # faint radial shine
      dx = (x - w * 0.72) / w;
      dy = (y - h * 0.18) / h;
      shine = exp(-(dx * dx + dy * dy) / 0.035) * 28;

      rr = int(r + shine); gg = int(g + shine); bb = int(b + shine);
      if (rr > 255) rr = 255; if (gg > 255) gg = 255; if (bb > 255) bb = 255;

      printf "%d %d %d ", rr, gg, bb;
    }
    printf "\n";
  }
}' > "$WALL"

info "Creating Openbox theme: $THEME_NAME"
cat > "$USER_HOME/.themes/$THEME_NAME/openbox-3/themerc" <<EOF
# $THEME_NAME - Aqua/Panther/Tiger-inspired Openbox theme.
# Generated by macosx-bsd-eye.sh

border.width: 1
padding.width: 6
padding.height: 4
window.client.padding.width: 0
window.handle.width: 4
window.active.border.color: $BOT
window.inactive.border.color: #9ca6ad

window.active.title.bg: gradient vertical
window.active.title.bg.color: $TOP
window.active.title.bg.colorTo: $BOT
window.active.label.bg: parentrelative
window.active.label.text.color: $TITLE_TEXT
window.active.label.text.font: shadow=y:shadowtint=35:shadowoffset=1

window.inactive.title.bg: gradient vertical
window.inactive.title.bg.color: $INACTIVE_TOP
window.inactive.title.bg.colorTo: $INACTIVE_BOT
window.inactive.label.bg: parentrelative
window.inactive.label.text.color: #586069

window.active.handle.bg: flat solid
window.active.handle.bg.color: $BOT
window.inactive.handle.bg: flat solid
window.inactive.handle.bg.color: $INACTIVE_BOT
window.active.grip.bg: flat solid
window.active.grip.bg.color: $TOP
window.inactive.grip.bg: flat solid
window.inactive.grip.bg.color: $INACTIVE_TOP

window.active.button.unpressed.bg: gradient vertical
window.active.button.unpressed.bg.color: #ffffff
window.active.button.unpressed.bg.colorTo: $MID
window.active.button.unpressed.image.color: #ffffff

window.active.button.hover.bg: gradient vertical
window.active.button.hover.bg.color: #ffffff
window.active.button.hover.bg.colorTo: $TOP
window.active.button.hover.image.color: #ffffff

window.active.button.pressed.bg: gradient vertical
window.active.button.pressed.bg.color: $BOT
window.active.button.pressed.bg.colorTo: #ffffff
window.active.button.pressed.image.color: #ffffff

window.inactive.button.unpressed.bg: gradient vertical
window.inactive.button.unpressed.bg.color: #ffffff
window.inactive.button.unpressed.bg.colorTo: #b8b8b8
window.inactive.button.unpressed.image.color: #777777

menu.border.width: 1
menu.border.color: #8fa8c2
menu.title.bg: gradient vertical
menu.title.bg.color: #ffffff
menu.title.bg.colorTo: $MID
menu.title.text.color: #12365c
menu.items.bg: flat solid
menu.items.bg.color: #f8fbff
menu.items.text.color: #10233f
menu.items.active.bg: gradient vertical
menu.items.active.bg.color: #d9efff
menu.items.active.bg.colorTo: $MID
menu.items.active.text.color: #ffffff
menu.separator.color: #a7bfd6

osd.border.width: 1
osd.border.color: $BOT
osd.bg: gradient vertical
osd.bg.color: #ffffff
osd.bg.colorTo: $MID
osd.label.text.color: #12365c
EOF

info "Creating Openbox rc.xml with old Mac-like left-side window buttons..."
cat > "$USER_HOME/.config/openbox/rc.xml" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<openbox_config xmlns="http://openbox.org/3.4/rc"
 xmlns:xi="http://www.w3.org/2001/XInclude">

  <resistance>
    <strength>10</strength>
    <screen_edge_strength>20</screen_edge_strength>
  </resistance>

  <focus>
    <focusNew>yes</focusNew>
    <followMouse>no</followMouse>
    <focusLast>yes</focusLast>
    <underMouse>no</underMouse>
    <focusDelay>200</focusDelay>
    <raiseOnFocus>no</raiseOnFocus>
  </focus>

  <placement>
    <policy>Smart</policy>
    <center>yes</center>
    <monitor>Primary</monitor>
  </placement>

  <theme>
    <name>$THEME_NAME</name>
    <!-- C=close, I=minimize/iconify, M=maximize, L=label. Old-Mac-ish left buttons. -->
    <titleLayout>CIML</titleLayout>
    <keepBorder>yes</keepBorder>
    <animateIconify>yes</animateIconify>
    <font place="ActiveWindow">
      <name>DejaVu Sans</name>
      <size>10</size>
      <weight>bold</weight>
      <slant>normal</slant>
    </font>
    <font place="InactiveWindow">
      <name>DejaVu Sans</name>
      <size>10</size>
      <weight>normal</weight>
      <slant>normal</slant>
    </font>
    <font place="MenuHeader">
      <name>DejaVu Sans</name>
      <size>10</size>
      <weight>bold</weight>
      <slant>normal</slant>
    </font>
    <font place="MenuItem">
      <name>DejaVu Sans</name>
      <size>10</size>
      <weight>normal</weight>
      <slant>normal</slant>
    </font>
  </theme>

  <desktops>
    <number>4</number>
    <firstdesk>1</firstdesk>
    <names>
      <name>Finder</name>
      <name>Terminal</name>
      <name>Web</name>
      <name>BSD</name>
    </names>
    <popupTime>875</popupTime>
  </desktops>

  <resize>
    <drawContents>yes</drawContents>
    <popupShow>Nonpixel</popupShow>
    <popupPosition>Center</popupPosition>
  </resize>

  <keyboard>
    <chainQuitKey>C-g</chainQuitKey>

    <keybind key="A-Return">
      <action name="Execute"><command>xterm</command></action>
    </keybind>

    <keybind key="A-space">
      <action name="ShowMenu"><menu>root-menu</menu></action>
    </keybind>

    <keybind key="A-Tab">
      <action name="NextWindow"/>
    </keybind>

    <keybind key="A-F4">
      <action name="Close"/>
    </keybind>

    <keybind key="W-r">
      <action name="Reconfigure"/>
    </keybind>
  </keyboard>

  <mouse>
    <dragThreshold>8</dragThreshold>
    <doubleClickTime>200</doubleClickTime>
    <screenEdgeWarpTime>400</screenEdgeWarpTime>
    <screenEdgeWarpMouse>false</screenEdgeWarpMouse>
  </mouse>

  <menu>
    <file>menu.xml</file>
    <hideDelay>200</hideDelay>
    <middle>no</middle>
    <submenuShowDelay>100</submenuShowDelay>
    <applicationIcons>yes</applicationIcons>
    <manageDesktops>yes</manageDesktops>
  </menu>

  <applications>
  </applications>
</openbox_config>
EOF

info "Creating Openbox menu..."
cat > "$USER_HOME/.config/openbox/menu.xml" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<openbox_menu xmlns="http://openbox.org/3.4/menu">
  <menu id="root-menu" label="AquaBSD">
    <item label="Terminal">
      <action name="Execute"><command>xterm</command></action>
    </item>
    <item label="Firefox">
      <action name="Execute"><command>firefox</command></action>
    </item>
    <item label="File manager">
      <action name="Execute"><command>pcmanfm</command></action>
    </item>
    <separator/>
    <item label="GTK theme settings">
      <action name="Execute"><command>lxappearance</command></action>
    </item>
    <item label="Reconfigure Openbox">
      <action name="Reconfigure"/>
    </item>
    <separator/>
    <item label="Exit Openbox">
      <action name="Exit"/>
    </item>
  </menu>
</openbox_menu>
EOF

info "Creating picom compositor config..."
cat > "$USER_HOME/.config/picom/picom.conf" <<'EOF'
# Aqua-ish X11 compositor settings.
backend = "xrender";
vsync = false;

shadow = true;
shadow-radius = 18;
shadow-offset-x = -7;
shadow-offset-y = 7;
shadow-opacity = 0.38;

fading = true;
fade-in-step = 0.045;
fade-out-step = 0.045;
fade-delta = 7;

inactive-opacity = 0.96;
active-opacity = 1.0;
frame-opacity = 0.92;
menu-opacity = 0.94;

corner-radius = 8;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.92; };
  menu = { shadow = true; opacity = 0.94; };
  dropdown_menu = { shadow = true; opacity = 0.94; };
  popup_menu = { shadow = true; opacity = 0.94; };
  dock = { shadow = false; };
  desktop = { shadow = false; };
};
EOF

info "Creating tint2 dock-like bottom panel..."
cat > "$USER_HOME/.config/tint2/tint2rc" <<EOF
# AquaBSD dock-like tint2 panel.

rounded = 15
border_width = 1
background_color = $PANEL 78
border_color = #ffffff 70

rounded = 10
border_width = 1
background_color = #ffffff 50
border_color = $ACCENT 45

rounded = 10
border_width = 1
background_color = $ACCENT 70
border_color = #ffffff 80

panel_items = LTSC
panel_size = 70% 48
panel_margin = 0 12
panel_padding = 8 4 8
panel_position = bottom center horizontal
panel_layer = top
panel_background_id = 1
wm_menu = 1
panel_dock = 0
panel_pivot_struts = 0

launcher_padding = 8 4 8
launcher_background_id = 0
launcher_icon_size = 32
launcher_item_app = /usr/local/share/applications/xterm.desktop
launcher_item_app = /usr/local/share/applications/firefox.desktop
launcher_item_app = /usr/local/share/applications/lxappearance.desktop

taskbar_mode = single_desktop
taskbar_padding = 4 4 4
taskbar_background_id = 0
taskbar_active_background_id = 0

task_icon = 1
task_text = 0
task_centered = 1
task_maximum_size = 42 38
task_padding = 6 4 6
task_background_id = 2
task_active_background_id = 3
task_iconified_background_id = 1
task_icon_asb = 100 0 0
task_active_icon_asb = 100 0 8
task_iconified_icon_asb = 65 0 0

systray = 1
systray_padding = 6 4 6
systray_background_id = 0
systray_icon_size = 22
systray_icon_asb = 100 0 0

clock = 1
time1_format = %H:%M
time1_font = DejaVu Sans Bold 10
clock_font_color = #12365c 100
clock_padding = 10 4
clock_background_id = 1

tooltip = 1
tooltip_padding = 8 6
tooltip_show_timeout = 0.5
tooltip_hide_timeout = 0.2
tooltip_background_id = 1
tooltip_font = DejaVu Sans 10
tooltip_font_color = #10233f 100
EOF

info "Creating GTK/XTerm cosmetic settings..."
cat > "$USER_HOME/.gtkrc-2.0" <<EOF
gtk-theme-name="Raleigh"
gtk-icon-theme-name="hicolor"
gtk-font-name="DejaVu Sans 10"
gtk-toolbar-style=GTK_TOOLBAR_ICONS
gtk-menu-images=1
gtk-button-images=1
EOF

cat > "$USER_HOME/.config/gtk-3.0/settings.ini" <<EOF
[Settings]
gtk-theme-name=Raleigh
gtk-icon-theme-name=hicolor
gtk-font-name=DejaVu Sans 10
gtk-toolbar-style=GTK_TOOLBAR_ICONS
gtk-menu-images=1
gtk-button-images=1
EOF

cat > "$USER_HOME/.Xresources" <<EOF
Xft.dpi: 96
Xft.antialias: true
Xft.hinting: true
Xft.hintstyle: hintslight
Xft.rgba: rgb

XTerm*faceName: DejaVu Sans Mono
XTerm*faceSize: 11
XTerm*utf8: 1
XTerm*saveLines: 4096
XTerm*scrollBar: false
XTerm*rightScrollBar: false
XTerm*background: #f7fbff
XTerm*foreground: #10233f
XTerm*cursorColor: $ACCENT
XTerm*pointerColor: $ACCENT
XTerm*color0: #10233f
XTerm*color1: #b32d2e
XTerm*color2: #2f7d32
XTerm*color3: #b57900
XTerm*color4: $ACCENT
XTerm*color5: #7a3db8
XTerm*color6: #00838f
XTerm*color7: #e8f4ff
XTerm*color8: #5b6b7a
XTerm*color9: #ff5a5f
XTerm*color10: #57c45d
XTerm*color11: #ffd166
XTerm*color12: #74b9ff
XTerm*color13: #b084f5
XTerm*color14: #4dd0e1
XTerm*color15: #ffffff
EOF

info "Creating Openbox autostart..."
cat > "$USER_HOME/.config/openbox/autostart" <<EOF
#!/bin/sh

# Load xterm/font colors.
if command -v xrdb >/dev/null 2>&1; then
  xrdb -merge "\$HOME/.Xresources" &
fi

# Nice cursor.
xsetroot -cursor_name left_ptr 2>/dev/null || true

# Wallpaper.
if command -v feh >/dev/null 2>&1; then
  feh --bg-fill "\$HOME/Pictures/${THEME_NAME}-wallpaper.ppm" &
else
  xsetroot -solid "$ACCENT" &
fi

# Shadows/transparency/fading.
if command -v picom >/dev/null 2>&1; then
  picom --config "\$HOME/.config/picom/picom.conf" &
fi

# Dock-like bottom panel.
if command -v tint2 >/dev/null 2>&1; then
  tint2 -c "\$HOME/.config/tint2/tint2rc" &
fi

# VirtualBox clipboard integration.
if command -v VBoxClient >/dev/null 2>&1; then
  VBoxClient --clipboard &
  VBoxClient --draganddrop &
  VBoxClient --seamless &
  VBoxClient --checkhostversion &
fi

# First terminal as safety net.
xterm &
EOF

chmod +x "$USER_HOME/.config/openbox/autostart"

info "Ensuring ~/.xinitrc starts Openbox..."
cat > "$USER_HOME/.xinitrc" <<'EOF'
#!/bin/sh
exec openbox-session
EOF
chmod +x "$USER_HOME/.xinitrc"

info "Fixing ownership..."
chown -R "$USER_NAME:$USER_NAME" \
  "$USER_HOME/.config" \
  "$USER_HOME/.themes" \
  "$USER_HOME/Pictures" \
  "$USER_HOME/.Xresources" \
  "$USER_HOME/.gtkrc-2.0" \
  "$USER_HOME/.xinitrc"

cat <<EOF

DONE. Applied profile: $PROFILE

Run as user '$USER_NAME':
  startx

Inside Openbox:
  Alt+Enter  -> xterm
  Alt+Space  -> Openbox menu
  Right-click desktop -> menu
  Win+r      -> reconfigure Openbox

Profiles:
  sh macosx-bsd-eye.sh $USER_NAME aqua
  sh macosx-bsd-eye.sh $USER_NAME graphite
  sh macosx-bsd-eye.sh $USER_NAME tiger

Note:
  This is Aqua-inspired, not Apple assets. It is intentionally lightweight:
  Openbox + picom + tint2 + feh + xterm.
EOF
